version: "3.8"
  
networks: 
  product_network:
volumes: 
  product_db_volume:

services:

  product_db_image:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    networks: 
      - product_network
    environment: 
      - POSTGRES_USER=product_user
      - POSTGRES_PASSWORD=product_password
      - POSTGRES_DB=product_db
    volumes:
      - product_db_volume:/var/postgresql/data

  product_api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "9000:9000"
    depends_on: 
      - product_db_image
    networks: 
      - product_network
    environment:
      - PORT=9000
      - NODE_ENV=production
      - TOKEN_KEY=thisismenttobeasecuredtokenkey
      - DB_NAME=product_db
      - DB_USER=product_user
      - DB_PASSWORD=product_password
      - DB_HOST=product_db_image
      - DB_PORT=5432
    
  product_proxy:
    restart: always
    build:
      dockerfile: /proxy/Dockerfile
      context: ./
    networks: 
      - product_network
    ports:
      - "80:80"
    depends_on: 
      - product_api
      - product_db_image

