version: "3.8"
    
volumes: 
  product_db_volume:

# For development
# For full stack developers

services:

  product_server_postgres_image:
    image: postgres:14-alpine
    ports:
      - 5434:5432
    environment: 
      - POSTGRES_USER=product_user
      - POSTGRES_PASSWORD=product_password
      - POSTGRES_DB=product_db
    volumes:
      - product_db_volume:/var/postgresql/data
